version: "3"
services:
   backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - NODE_ENV=development
