version: "3.8"

services:
  # Linux AMD64 build
  build-linux:
    build:
      context: .
      dockerfile: ./docker/linux/AMD64
    platform: linux/amd64
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TAURI_PRIVATE_KEY=${TAURI_PRIVATE_KEY}
      - TAURI_KEY_PASSWORD=${TAURI_KEY_PASSWORD}
    command: "cargo tauri build --target x86_64-unknown-linux-gnu"
  
  # Linux ARM build
  build-linux-arm:
    build:
      context: .
      dockerfile: ./docker/linux/ARM
    platform: linux/arm64
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TAURI_PRIVATE_KEY=${TAURI_PRIVATE_KEY}
      - TAURI_KEY_PASSWORD=${TAURI_KEY_PASSWORD}
    command: "cargo tauri build --target aarch64-unknown-linux-gnu"

  # macOS build
  build-macos:
    build:
      context: .
      dockerfile: ./docker/mac/
    platform: darwin/amd64
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TAURI_PRIVATE_KEY=${TAURI_PRIVATE_KEY}
      - TAURI_KEY_PASSWORD=${TAURI_KEY_PASSWORD}
    command: "cargo tauri build --target x86_64-apple-darwin"

  # Windows build
  build-windows:
    build:
      context: .
      dockerfile: ./docker/windows/
    platform: windows/amd64
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TAURI_PRIVATE_KEY=${TAURI_PRIVATE_KEY}
      - TAURI_KEY_PASSWORD=${TAURI_KEY_PASSWORD}
    command: "cargo tauri build --target x86_64-pc-windows-msvc"
