version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - '4000:4000'
      - '3000:3000'
    environment:
      - NODE_ENV=development

  testing:
    build:
      context: .
      dockerfile: Dockerfile.testing
    volumes:
      - .:/app
    # depends_on:
    #   - backend
    #   - frontend
    command: ['sh', '-c', 'cargo test && cd /app && npm test']
